### ISSUE TITLE
Project-level docker-compose

### ISSUE THREAD

**Issue by samthorold** [recipes-org/infra#15]
```yaml
services:
  recipes:
    build: ../svc-recipes
    env_file:
      - .env
    ports:
      - 8008:8008
    depends_on:
      - db
  ingredients:
    build: ../svc-ingredients
    env_file:
      - .env
    ports:
      - 8009:8008
    depends_on:
      - db
  measurements:
    build: ../svc-measurements
    env_file:
      - .env
    ports:
      - 8010:8008
    depends_on:
      - db
 
  db:
    image: postgres:15-bookworm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
 
volumes:
    colunch_db:
```
