### ISSUE TITLE
Run container registry garbage collection daily

### ISSUE THREAD

**Issue by samthorold** [recipes-org/infra#3]
`doctl registry garbage-collection start --include-untagged-manifests`

**Comment by samthorold** [comment]
```yaml
on:
  schedule:
    - cron:  "37 4 * * *"
```
